### ISSUE TITLE
Slide name visibility

### ISSUE THREAD

**Issue by jesperkers** [Falcury/slideviewer#13]
Slide name is not visible when opened

**Comment by Falcury** [comment]
Added in 40239c1963c2b387810fe3b8c208214ca23e07d4. The window title now changes to match the filename of the slide that has been opened.

**Comment by Falcury** [comment]
Also tested and fixed on Linux: 9d1b3e846678a256d418d60505ac3685048227b8.

**Comment by Falcury** [comment]
@jesperkers I released a new version with the fix:
https://github.com/Falcury/slideviewer/releases/tag/0.31
