### ISSUE TITLE
License issue

### ISSUE THREAD

**Issue by andreped** [Falcury/slideviewer#17]
Is there a reason why you used GPL license for this project?

We would like to add iSyntax support to our open software [FastPathology](https://github.com/AICAN-Research/FAST-Pathology). I have been following this project, and was not aware that you managed to add support for iSyntax (see [this release](https://github.com/amspath/slidescape/releases/tag/0.34)).

However, if we were to take inspiration of this code, we would run into licensing issues, as our code would also need to be GPL licenced, where we instead would like to have a more permissive license, BSD 2-clause.

**Comment by andreped** [comment]
Also, more importantly, I thought reverse engineering of this format was not allowed. That is, we were not allowed to make our own iSyntax readers, but had to use Philips SDK. Maybe I'm wrong? Not even QuPath supports it (see docs [here](https://qupath.readthedocs.io/en/stable/docs/intro/formats.html#isyntax-philips)).

This is what @petebankhehad has to say regarding the issue (see [this thread](https://forum.image.sc/t/integrating-isyntax-reader-openphi/75956/2)):
```
I’m afraid not – from the docs, it seems that openphi still requires using the Philips SDK. And it’s written in Python, whereas QuPath is written in Java, so it doesn’t really simplify things.

There are a few discussions that are related: [Search results for 'isyntax' - Image.sc Forum](https://forum.image.sc/search?q=isyntax)

As I understand it, the iSyntax SDK

* isn’t available under an open source license
* isn’t available for all the platforms where QuPath runs (Windows, Linux, Mac)
* may not even be (reliably) accessible (e.g. see [here 2](https://forum.image.sc/t/advice-for-accessing-philips-sdk/63570/9))

From a practical perspective, I don’t work with iSyntax images myself and unfortunately don’t have any time on working on an integration anyway.

QuPath support could potentially be added via an extension written by someone else, as long as it can somehow fit with QuPath’s (open-source) license and Philips’ licensing.
```

Might be that you are allowed to reverse engineer the format, but I highly doubt it. @petebankhead, any thoughts?

**Comment by Falcury** [comment]
Hi, @andreped!

Yes, I am aware that the GPL license is problematic in this regard. My intent is to split off the iSyntax-related code (and maybe some other parts too) into a stand-alone library with a more permissive license.

You might also want to ask @innovationcore about this, he has also been making efforts to integrate the iSyntax code from Slidescape into other projects (see here: https://medicine.ai.uky.edu/2022/08/24/library-support-for-philips-isyntax-format/).

As to the second question: actually, Philips released the iSyntax file format specification in 2020. They have since unfortunately closed down again their public OpenPathology portal website where the specification (including also example code and files) used to be available for download. However, the specification itself is still out in the wild and (semi-)publicly available. I only used the specification documents and code examples that Philips released themselves for my implementation. There was no reverse engineering of the Philips SDK involved!

**Comment by andreped** [comment]
> However, the specification itself is still out in the wild and (semi-)publicly available. I only used the specification documents and code examples that Philips released themselves for my implementation. There was no reverse engineering of the Philips SDK involved!

Sadly, I'm not sure that makes much different. Even if you had an random algorithm generator that by chance managed to parse the iSyntax format, I believe Philips own the right to the format and the only accepted way to read it is through their own iSyntax SDK. However, as you have seen, parts of the documentations on this has been removed by Philips (for some unknown reason), and thus we can only speculate. _Partly-public_ is still proprietary IMO, which means that I personally cannot use it for fully open software, as I aim to make software that is fully public without any real proprietary limitations.

If you ever get in touch with anyone from Philips or similar regarding this issue, please, let me know, but right now 1) I cannot use this code directly as it is GPL licensed (as it would result in my code also being GPL-licenced) and 2) the iSyntax format itself is cursed and I'm not I could use this code without it impacting the license of my own code (somewhat similar to GPL but not the same).

However, if you were to release a standalone library with an open license, I would be very interested :] Looking forward to it!

**Comment by Falcury** [comment]
> If you ever get in touch with anyone from Philips or similar regarding this issue, please, let me know

The people I have talked to from Philips were enthousiastic about it and indeed quite supportive. As far as I am aware there is no legal issue with my implementation (at least, not for me personally).

Edit: for reference, also see the discussion on this topic here: https://github.com/openslide/openslide/issues/145

> However, if you were to release a standalone library with an open license, I would be very interested :] Looking forward to it!

I guess I should get on with it and make it a priority, then ;)

**Comment by andreped** [comment]
> I guess I should get on with it and make it a priority, then ;)

We will be able to test this quite fast after you have made an attempt btw, so keep me updated :]



> Edit: for reference, also see the discussion on this topic here: [openslide/openslide#145](https://github.com/openslide/openslide/issues/145)

As I said, I'm still not convinced you can do whatever you want, as they own the rights with that format. But idk. Would love if someone at Philips could shine new light on this topic. IMO, the Philips SDK is not really that useful as it is terribly documented, as discussed in the thread you mentioned. The SDK also has a proprietary license, making it unsuitable for some applications, such as mine. But I'm not a lawyer nor know every detail into this SDK and the iSyntax format in general. I'm just being cautious.

**Comment by jeffchchang** [comment]
Just wanted to comment and say that I'd also be very interested in using this code if you were to release it with a more open license! I'm also having trouble even finding how to access the [Philips SDK](https://www.openpathology.philips.com/) - seems like the link is dead now.

**Comment by Falcury** [comment]
I extracted the iSyntax-related parts from the Slidescape codebase and re-released them with a BSD 2-Clause license here:
https://github.com/amspath/libisyntax

Work is ongoing with @alex-virodov and @bgilbert to develop the library further. The aim is to facilitate the addition of iSyntax support into e.g. OpenSlide.

Also see the discussion here:
https://github.com/openslide/openslide/issues/433
