### ISSUE TITLE
Upcoming OpenSlide release will change library filename

### ISSUE THREAD

**Issue by bgilbert** [Falcury/slideviewer#18]
The next OpenSlide release, 4.0.0, will include some incompatible API changes.  Those are unlikely to affect you directly, but as a consequence, OpenSlide's [soname](https://en.wikipedia.org/wiki/Soname) will change.  This will change the library filename to `libopenslide-1.dll` on Windows, `libopenslide.1.dylib` on macOS, and `libopenslide.so.1` on Linux.  Since Slidescape loads OpenSlide by filename on Windows, you may want to proactively add support for the new name so Slidescape will work with the new release.

For more information, see https://github.com/openslide/openslide/pull/413.  If you have any questions, please ask!

**Comment by Falcury** [comment]
@bgilbert Thanks for the heads-up! 

I suppose on Windows we should check for `libopenslide-1.dll` first, then `libopenslide-0.dll` if that one doesn't exist.

**Comment by Falcury** [comment]
This was addressed in https://github.com/amspath/slidescape/commit/6400311e567c4b714f4480a2d229a6617998a9bf with a further fix in f90dcdc4a78d29f6a672cee749b851252c2b6dc9. Closing this as completed.
